conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('socialmedia.urls', namespace='social')),
              ]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socialmedia/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm

app_name = 'social'
urlpatterns = [
    path('', views.profile, name='profile'),
    # path('login/', auth_views.LoginView.as_view(authentication_form=LoginForm), name='login', ),
    path('logout/', views.log_out, name='logout', ),
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegistrationView.as_view(), name='register'),
    path('user/edit/', views.edit_user, name='edit_account'),

    path('ticket/', views.ticket, name="ticket"),

    path('password-change/', auth_views.PasswordChangeView.as_view(success_url='done'), name="password_change"),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),

    path('password-reset/', auth_views.PasswordResetView.as_view(success_url='done'), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url='/login'),
         name="password_reset_confirm"),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),

    path('posts/', views.post_list, name="posts_list", ),
    path('posts/<slug:tag_slug>/', views.post_list, name="post_list_by_tag"),
    path('posts/post/create_post/', views.create_post, name="create_post"),
    path('posts/detail/<pk>', views.post_detail, name="post_detail"),
    path('posts/<post_id>/comment', views.post_comment, name="post_comment"),
    path('like_post/', views.like_post, name="like_post"),

    path('users/', views.user_list, name='user_list'),
    path('users/<username>/', views.user_detail, name='user_detail'),
    path('follow/', views.user_follow, name='user_follow'),

]

templates/social/list.html
{#{% if tag %}#}
{#    <h2>post tagged with {{ tag.name }} </h2>#}
{##}
{#{% endif %}#}
{##}
{#{% for post in posts %}#}
{#    #}
{#    <a href="{{ post.get_absolute_url }}">{{ post.description|truncatewords:20|linebreaks }}</a>#}
{#    published at {{ post.created }} by {{ post.author }}#}
{#    <br>#}
{#    {% for tag in post.tags.all %}#}
{#        <a href="{% url 'social:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>#}
{#    {% endfor %}#}
{#    <br>#}

{#{% endfor %}#}
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% if tag %}
    <h2>post tagged with {{ tag.name }} </h2>

{% endif %}
    <div class="grid grid-cols-2 ">
 
{% for post in posts %}
 
<div class="p-3 px-6 min-h-48 flex justify-center  " data-post-id="{{ post.id }}" style="cursor: auto;">
{#  <custom-card3>#}
    <div class="rounded-md shadow-md sm:w-96 bg-coolGray-900 text-coolGray-100">
      <div class="flex items-center justify-between p-3" style="cursor: auto;">
        <div class="flex items-center space-x-2" style="cursor: auto;">
            <a href="{{ post.author.get_absolute_url }}">
           {% if post.author.photo %}     
          <img src="{{ post.author.photo.url }}" alt="" class="object-cover object-center w-8 h-8 rounded-full shadow-sm bg-coolGray-500 border-coolGray-700" style="cursor: auto;">
               {% else %}
                <img src="{% static 'image/profile/avatar.png' %}" alt="" class="object-cover object-center w-8 h-8 rounded-full shadow-sm bg-coolGray-500 border-coolGray-700" style="cursor: auto;">
            {% endif %}
            </a>
                <div class="-space-y-1" style="cursor: auto;">
            <h2 class="text-sm font-semibold leading-none" style="cursor: auto;">{{ post.author }}</h2>
            <span class="inline-block text-xs leading-none text-coolGray-400" style="cursor: auto;">New York City</span>
          </div>
        </div>
        <button title="Open options" type="button">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-5 h-5 fill-current" style="cursor: auto;">
            <path d="M256,144a64,64,0,1,0-64-64A64.072,64.072,0,0,0,256,144Zm0-96a32,32,0,1,1-32,32A32.036,32.036,0,0,1,256,48Z"></path>
            <path d="M256,368a64,64,0,1,0,64,64A64.072,64.072,0,0,0,256,368Zm0,96a32,32,0,1,1,32-32A32.036,32.036,0,0,1,256,464Z"></path>
            <path d="M256,192a64,64,0,1,0,64,64A64.072,64.072,0,0,0,256,192Zm0,96a32,32,0,1,1,32-32A32.036,32.036,0,0,1,256,288Z"></path>
          </svg>
        </button>
      </div>
    <a href="{{ post.get_absolute_url }}">
    
      <img src='{{post.images.first.image_file.url }}' alt="" class="object-cover object-center w-full h-72 bg-coolGray-500" style="cursor: auto;">
    </a>
      <div class="p-3" style="cursor: auto;">
        <div class="flex items-center justify-between" style="cursor: auto;">
          <div class="flex items-center space-x-3">
            <button type="button" title="Like post" class="flex items-center justify-center">
{#              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-5 h-5 fill-current">#}
{#                <path d="M453.122,79.012a128,128,0,0,0-181.087.068l-15.511,15.7L241.142,79.114l-.1-.1a128,128,0,0,0-181.02,0l-6.91,6.91a128,128,0,0,0,0,181.019L235.485,449.314l20.595,21.578.491-.492.533.533L276.4,450.574,460.032,266.94a128.147,128.147,0,0,0,0-181.019ZM437.4,244.313,256.571,425.146,75.738,244.313a96,96,0,0,1,0-135.764l6.911-6.91a96,96,0,0,1,135.713-.051l38.093,38.787,38.274-38.736a96,96,0,0,1,135.765,0l6.91,6.909A96.11,96.11,0,0,1,437.4,244.313Z"></path>#}
{#              </svg>#}
                    {% if request.user in post.likes.all %}

                            <i class="like-button fa fa-heart heart text-red-700 " id="like-button{{ post.id }}" style="font-size:20px"></i>
                            

                        {% else %}

                            <i class="like-button fa fa-heart-o heart " id="like-button{{ post.id }}" style="font-size:20px"></i>
                            
                        {% endif %}
            </button>
            <button type="button" title="Add a comment" class="flex items-center justify-center">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-5 h-5 fill-current">
                <path d="M496,496H480a273.39,273.39,0,0,1-179.025-66.782l-16.827-14.584C274.814,415.542,265.376,416,256,416c-63.527,0-123.385-20.431-168.548-57.529C41.375,320.623,16,270.025,16,216S41.375,111.377,87.452,73.529C132.615,36.431,192.473,16,256,16S379.385,36.431,424.548,73.529C470.625,111.377,496,161.975,496,216a171.161,171.161,0,0,1-21.077,82.151,201.505,201.505,0,0,1-47.065,57.537,285.22,285.22,0,0,0,63.455,97L496,457.373ZM294.456,381.222l27.477,23.814a241.379,241.379,0,0,0,135,57.86,317.5,317.5,0,0,1-62.617-105.583v0l-4.395-12.463,9.209-7.068C440.963,305.678,464,262.429,464,216c0-92.636-93.309-168-208-168S48,123.364,48,216s93.309,168,208,168a259.114,259.114,0,0,0,31.4-1.913Z"></path>
              </svg>
            </button>
            <button type="button" title="Share post" class="flex items-center justify-center">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-5 h-5 fill-current">
                <path d="M474.444,19.857a20.336,20.336,0,0,0-21.592-2.781L33.737,213.8v38.066l176.037,70.414L322.69,496h38.074l120.3-455.4A20.342,20.342,0,0,0,474.444,19.857ZM337.257,459.693,240.2,310.37,389.553,146.788l-23.631-21.576L215.4,290.069,70.257,232.012,443.7,56.72Z"></path>
              </svg>
            </button>
          </div>
          <button type="button" title="Bookmark post" class="flex items-center justify-center">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-5 h-5 fill-current">
              <path d="M424,496H388.75L256.008,381.19,123.467,496H88V16H424ZM120,48V456.667l135.992-117.8L392,456.5V48Z"></path>
            </svg>
          </button>
        </div>
        <div class="flex flex-wrap items-center pt-3 pb-1" style="cursor: auto;">
          <div class="flex items-center space-x-2">
            <div class="flex -space-x-1">
              <img alt="" class="w-5 h-5 border rounded-full bg-coolGray-500 border-coolGray-800" src="https://stackdiary.com/140x100.png">
              <img alt="" class="w-5 h-5 border rounded-full bg-coolGray-500 border-coolGray-800" src="https://stackdiary.com/140x100.png">
              <img alt="" class="w-5 h-5 border rounded-full bg-coolGray-500 border-coolGray-800" src="https://stackdiary.com/140x100.png"><!---->
            </div>
            <span class="text-sm"> Liked by
              <span class="font-semibold"></span> 
              <span class="font-semibold">{{ post.likes.count }} person</span>
            </span>
          </div>
        </div>
        <div class="space-y-3" style="cursor: auto;">
          <p class="text-sm" style="cursor: auto;">
            <span class="text-base font-semibold">External_</span> {{ post.description|truncatewords:20|linebreaks }}
          </p>
                {% for tag in post.tags.all %}
        <a href="{% url 'social:post_list_by_tag' tag.slug %}" class="bg-cyan-700">{{ tag.name }}</a>
    {% endfor %}
{#          <input type="text" placeholder="Add a comment..." class="w-full py-0.5 bg-transparent border-none rounded text-sm pl-0 text-coolGray-100" style="cursor: auto;">#}
            <form method="post" action="{% url 'social:post_comment' post.id %}" >
                                                    {% csrf_token %}
                                                    {{ form.as_div }}
                                                  <div class="col-12">
                                                    
                                                  </div>
                                                </form>
        </div>
      </div>
    </div>
{#  </custom-card3>#}
</div>
 


{% endfor %}
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        
     $(document).ready(function() {
        $('#like-button1').click(function() {
            var  button = $(this);
            var post_id = $(this).closest('.post').data('post-id');

            $.ajax({
                type: 'POST',
                url: '{% url 'social:like_post' %}',
                data: {'post_id': post_id, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                success: function(data) {
                    if (data.liked){
                        
                        button.removeClass('fa fa-heart-o');
                        button.addClass('fa fa-heart text-red-700')
                        
                    } else {
                        button.removeClass('fa fa-heart text-red-700')
                        button.addClass('fa fa-heart-o');
                        
                        
                    }
                    $('#likes-count').text(data.likes_count);
                },
            });
        });

    });
    </script>
{% endblock %}

templates/social/post_detail.html
{#{{ post.description|linebreaks }}#}
{#published at {{ post.created }} by {{ post.author }}#}
{#<br>#}
{#{% for tag in post.tags.all %}#}
{#        <a href="{% url 'social:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>#}
{#        {% if not forloop.last %}, {% endif %}#}
{#{% endfor %}#}
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <!-- component -->
   
    <div class="post bg-gray-200 h-screen flex items-center justify-center w-full " data-post-id="{{ post.id }}">
        <div class="bg-white p-10 rounded-lg shadow-md w-1/4">
            <!-- User Info with Three-Dot Menu -->
            <div class="flex items-center justify-between mb-4">
                <div class="flex items-center space-x-2">
{#                    <img src="https://placekitten.com/40/40" alt="User Avatar" class="w-8 h-8 rounded-full">#}
                     {% if post.author.photo %}     
          <img src="{{ post.author.photo.url }}" alt="" class="w-8 h-8 rounded-full" style="cursor: auto;">
               {% else %}
                <img src="{% static 'image/profile/avatar.png' %}" alt="" class="w-8 h-8 rounded-full" style="cursor: auto;">
            {% endif %}
                    <div>
                        <p class="text-gray-800 font-semibold">{{ post.author }}</p>
                        <p class="text-gray-500 text-sm">{{ post.created }}</p>
                    </div>
                </div>
                <div class="text-gray-500 cursor-pointer">
                    <!-- Three-dot menu icon -->
{#                    				<button class="hover:bg-gray-50 rounded-full p-1">#}
{#                    					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">#}
{#                    						<circle cx="12" cy="7" r="1" />#}
{#                    						<circle cx="12" cy="12" r="1" />#}
{#                    						<circle cx="12" cy="17" r="1" />#}
{#                    					</svg>#}
{#                    				</button>#}
                </div>
            </div>
            <!-- Message -->
            <div class="mb-4">
                <p class="text-gray-800">{{ post.description|linebreaks }}
                    {% for tag in post.tags.all %}
                        <a href="{% url 'social:post_list_by_tag' tag.slug %}" class="bg-cyan-700">{{ tag.name }}</a>
                    {% endfor %}
                </p>
            </div>
            <!-- Image -->
            <div class="mb-4">
                <img src='{{ post.images.first.image_file.url }}' alt="Post Image"
                     class="w-full h-48 object-cover rounded-md">
            </div>
            <!-- Like and Comment Section -->
            <div class="flex items-center justify-between text-gray-500">
                <div class="flex items-center space-x-2">
                    <button class=" flex justify-center items-center gap-2 px-2 hover:bg-gray-50 rounded-full p-1">
                        {% if request.user in post.likes.all %}

                            <i class="fa fa-heart heart text-red-700" id="like-button"></i>
                            

                        {% else %}

                            <i class="fa fa-heart-o heart " id="like-button" ></i>
                            
                        {% endif %}
                    <span id="likes-count">{{ post.likes.count }} Likes</span>
                    </button>
                </div>
                <button class="flex justify-center items-center gap-2 px-2 hover:bg-gray-50 rounded-full p-1">
                    <svg width="22px" height="22px" viewBox="0 0 24 24" class="w-5 h-5 fill-current"
                         xmlns="http://www.w3.org/2000/svg">
                        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                        <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                        <g id="SVGRepo_iconCarrier">
                            <path fill-rule="evenodd" clip-rule="evenodd"
                                  d="M12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 13.5997 2.37562 15.1116 3.04346 16.4525C3.22094 16.8088 3.28001 17.2161 3.17712 17.6006L2.58151 19.8267C2.32295 20.793 3.20701 21.677 4.17335 21.4185L6.39939 20.8229C6.78393 20.72 7.19121 20.7791 7.54753 20.9565C8.88837 21.6244 10.4003 22 12 22ZM8 13.25C7.58579 13.25 7.25 13.5858 7.25 14C7.25 14.4142 7.58579 14.75 8 14.75H13.5C13.9142 14.75 14.25 14.4142 14.25 14C14.25 13.5858 13.9142 13.25 13.5 13.25H8ZM7.25 10.5C7.25 10.0858 7.58579 9.75 8 9.75H16C16.4142 9.75 16.75 10.0858 16.75 10.5C16.75 10.9142 16.4142 11.25 16 11.25H8C7.58579 11.25 7.25 10.9142 7.25 10.5Z"></path>
                        </g>
                    </svg>
                    <span>
                    {% with comments.count as comment_count %}
                        {{ comment_count }} Comment{{ comment_count|pluralize }}
                    {% endwith %}
                </span>
                </button>
            </div>
            <hr class="mt-2 mb-2">
            <p class="text-gray-800 font-semibold">Comment</p>
            <hr class="mt-2 mb-2">
            <div class="mt-4">
                <!-- Comment 1 -->
                {% for cm in comments %}
                    <div class="flex items-center space-x-2">
                        <img src="https://placekitten.com/32/32" alt="User Avatar" class="w-6 h-6 rounded-full">
                        <div>
                            <p class="text-gray-800 font-semibold">{{ cm.name }}</p>
                            <p class="text-gray-500 text-sm">{{ cm.body }}</p>
                        </div>
                    </div>
                {% endfor %}
            
            </div>
        </div>
    </div>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>

        
     $(document).ready(function() {
        $('#like-button').click(function() {
            var  button = $(this);

            $.ajax({
                type: 'POST',
                url: '{% url 'social:like_post' %}',
                data: {'post_id': {{post.id}}, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                success: function(data) {
                    if (data.liked){
                        
                        button.removeClass('fa fa-heart-o');
                        button.addClass('fa fa-heart text-red-700')
                        
                    } else {
                        button.removeClass('fa fa-heart text-red-700')
                        button.addClass('fa fa-heart-o');
                        
                        
                    }
                    $('#likes-count').text(data.likes_count);
                },
            });
        });

    });
    </script>
{% endblock %}

templates/social/profile.html
{% extends 'base.html' %}
{% load static %}
{% block extr-ahead %}
    <style>
        .pb-full {
            padding-bottom: 100%;
        }

        /* hide search icon on search focus */
        .search-bar:focus + .fa-search {
            display: none;
        }

        @media screen and (min-width: 768px) {
            .post:hover .overlay {
                display: block;
            }
        }

    </style>
{% endblock %}
{% block content %}

    <div
            class="card  min-w-sm border border-white bg-transparent   transition-shadow shadow-xl hover:shadow-xl min-w-max w-full">
    <!---->
    <div class="w-full card__media"><img
            src="https://image.freepik.com/free-vector/abstract-binary-code-techno-background_1048-12836.jpg"
            class="h-48 w-full"></div>
    <div class="  card__media--aside "></div>
    <div class="flex items-center p-4">
    <div class="relative flex flex-col items-center w-full">
        <div
                class="h-24 w-24 md rounded-full relative avatar flex items-end justify-end text-purple-600 min-w-max absolute -top-16 flex bg-purple-200 text-purple-100 row-start-1 row-end-3 text-purple-650 ring-1 ring-white">
{#            <img class="h-24 w-24 md rounded-full relative" src="{{ request.user.photo.url }}"#}
{#                 alt="">#}
             {% if request.user.photo %}
		 <img class="h-24 w-24 md rounded-full relative" src="{{ request.user.photo.url }}"
                 alt="">
        {% else %}
        <img src="{% static 'image/profile/avatar.png' %}" alt="" class="h-24 w-24 md rounded-full relative">
            
        {% endif %}
            <div class="absolute"></div>
        </div>
        <div class="flex flex-col space-y-1 justify-center items-center -mt-12 w-full">
            <span class="text-md whitespace-nowrap text-gray-800 font-semibold">{{ user.username }}</span><span
                class="text-md whitespace-nowrap text-gray-600">{{ user.get_full_name }}</span>
            <p class="text-sm text-gray-500">
                {{ user.bio }}
            </p>
            <div class="py-2 flex space-x-2">
{#                <button class="flex justify-center  max-h-max whitespace-nowrap focus:outline-none  focus:ring  focus:border-blue-300 rounded max-w-max border bg-transparent border-purple-700 text-purple-700 hover:border-purple-800 hover:border-purple-800 px-4 py-1 flex items-center hover:shadow-lg">#}
{#                    <span class="mr-2"></span>FOLLOW<span class="ml-2"></span></button>#}
                {#                                <button class="flex justify-center  max-h-max whitespace-nowrap focus:outline-none  focus:ring  focus:border-blue-300 rounded max-w-max text-gray-100 bg-green-500 hover:bg-green-600 px-4 py-1 flex items-center hover:shadow-lg"><span class="mr-2"><svg height="20" width="20" viewBox="0 0 32 32" class="fill-current text-red-100"><path d="M22.5,4c-2,0-3.9,0.8-5.3,2.2L16,7.4l-1.1-1.1C12,3.3,7.2,3.3,4.3,6.2c0,0-0.1,0.1-0.1,0.1c-3,3-3,7.8,0,10.8L16,29	l11.8-11.9c3-3,3-7.8,0-10.8C26.4,4.8,24.5,4,22.5,4z"></path></svg></span>SPONSOR <span class="ml-2"></span></button>#}
            </div>
            <div
                    class="py-4 flex justify-center items-center w-full divide-x divide-gray-400 divide-solid">
                <span class="text-center px-2"><span class="font-bold text-gray-700">{{ user.followers.count }}</span><span
                        class="text-gray-600"> followers</span></span><span class="text-center px-2"><span
                    class="font-bold text-gray-700">{{ user.following.count }}</span><span class="text-gray-600"> following</span></span><span
                    class="text-center px-2"><span class="font-bold text-gray-700">{{ my_posts.count }}</span><span class="text-gray-600"> post</span></span>
            </div>
        </div>
        <div class="flex flex-wrap w-full">
            {% for post in my_posts %}
            <div class="w-1/3 p-px md:px-3">
                <a href="{{ post.get_absolute_url }}">
                    <article class="post bg-gray-100 text-white relative pb-full md:mb-6">
                        <img class="w-full h-full absolute left-0 top-0 object-cover"
                             src="{{post.images.first.image_file.url }}"
                             alt="image">

                        <i class="fas fa-video absolute right-0 top-0 m-1"></i>

                        <!-- overlay-->
                        <div class="overlay bg-gray-800 bg-opacity-25 w-full h-full absolute 
                                                left-0 top-0 hidden">
                            <div class="flex justify-center items-center 
                                                    space-x-4 h-full">
                                  <span class="p-2">
                                    <i class="fa fa-heart-o" style="font-size:20px"></i>
                                    {{ post.likes.count }}
                                  </span>

                                <span class="p-2">
                                   <i class="fa fa-comment-o" style="font-size:20px"></i>
                                    {{ post.comments.count }}
                                  </span>
                            </div>
                        </div>

                    </article>
                </a>
            </div>
                {% endfor %}
        </div>
{#    {% endfor %}#}


    </div>
{#    {% endwith %}#}
    {#				</div>#}
    <!---->

    <!---->
    <!---->
    <!---->
    {#				<div#}
    {#			class="card  min-w-sm border border-gray-700 bg-gray-700 text-gray-50   transition-shadow shadow-xl hover:shadow-xl min-w-max">#}
    {#			<!---->#}
    {#			<div class="w-full card__media"><img src="https://image.freepik.com/free-vector/abstract-binary-code-techno-background_1048-12836.jpg" class="h-48 w-96"></div>#}
    {#			#}
    {#				<div class="flex items-center p-4">#}
    {#					<div class="relative flex flex-col items-center w-full">#}
    {#						<div#}
    {#							class="h-24 w-24 md rounded-full relative avatar flex items-end justify-end text-purple-400 min-w-max absolute -top-16 flex bg-purple-200 text-purple-100 row-start-1 row-end-3 text-purple-650 ring-1 ring-white">#}
    {#							<img class="h-24 w-24 md rounded-full relative" src="https://avatars3.githubusercontent.com/u/11801238?v=4" alt="">#}
    {#							<div class="absolute"></div>#}
    {#						</div>#}
    {#						<div class="flex flex-col space-y-1 justify-center items-center -mt-12 w-full">#}
    {#							<span class="text-md whitespace-nowrap text-gray-50 font-semibold">Brahim</span><span class="text-md whitespace-nowrap text-gray-100">boussadjra</span>#}
    {#							<p class="text-sm text-gray-200">#}
    {#								I can't start my day without a coffee cup#}
    {#							</p>#}
    {#							<div class="py-2 flex space-x-2">#}
    {#								<button class="flex justify-center  max-h-max whitespace-nowrap focus:outline-none  focus:ring  focus:border-blue-300 rounded max-w-max border bg-transparent border-purple-400 text-purple-400 hover:border-purple-800 hover:border-purple-500 px-4 py-1 flex items-center hover:shadow-lg"><span class="mr-2"></span>FOLLOW<span class="ml-2"></span></button><button class="flex justify-center  max-h-max whitespace-nowrap focus:outline-none  focus:ring  focus:border-blue-300 rounded max-w-max text-gray-100 bg-green-500 hover:bg-green-600 px-4 py-1 flex items-center hover:shadow-lg"><span class="mr-2"><svg height="20" width="20" viewBox="0 0 32 32" class="fill-current text-red-100"><path d="M22.5,4c-2,0-3.9,0.8-5.3,2.2L16,7.4l-1.1-1.1C12,3.3,7.2,3.3,4.3,6.2c0,0-0.1,0.1-0.1,0.1c-3,3-3,7.8,0,10.8L16,29	l11.8-11.9c3-3,3-7.8,0-10.8C26.4,4.8,24.5,4,22.5,4z"></path></svg></span>SPONSOR <span class="ml-2"></span></button>#}
    {#							</div>#}
    {#							<div#}
    {#								class="py-4 flex justify-center items-center w-full divide-x divide-gray-400 divide-solid">#}
    {#								<span class="text-center px-2"><span class="font-bold text-gray-50">56</span><span class="text-gray-100"> followers</span></span><span class="text-center px-2"><span class="font-bold text-gray-50">112</span><span class="text-gray-100"> following</span></span><span class="text-center px-2"><span class="font-bold text-gray-50">27</span><span class="text-gray-100"> repos</span></span>#}
    {#							</div>#}
    {#						</div>#}
    {#					</div>#}
    {#				</div>#}
    {#				<!---->#}
    {#			</div>#}
    {#		</div>#}
    {#	</div>#}
{% endblock %}